# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

CC=/usr/bin//gcc
AS=/usr/bin//gcc
GC=/home/greetlist/go/bin/go
FC=/usr/bin//gfortran
MM=/usr/bin//gcc
MXX=/usr/bin//gcc
CXX=/usr/bin//gcc

GCLD=/home/greetlist/go/bin/go
FCLD=/usr/bin//gfortran
LD=/usr/bin//g++
GCAR=/home/greetlist/go/bin/go
AR=/usr/bin//ar
FCSH=/usr/bin//gfortran
SH=/usr/bin//g++

simd_performance_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -DNDEBUG
simd_performance_LDFLAGS=-m64 -s

default:  simd_performance

all:  simd_performance

.PHONY: default all  simd_performance

simd_performance: build/linux/x86_64/release/simd_performance
build/linux/x86_64/release/simd_performance: build/.objs/simd_performance/linux/x86_64/release/src/AVXCalculator.cc.o build/.objs/simd_performance/linux/x86_64/release/src/main.cc.o build/.objs/simd_performance/linux/x86_64/release/src/SSECalculator.cc.o
	@echo linking.release simd_performance
	@mkdir -p build/linux/x86_64/release
	@$(LD) -o build/linux/x86_64/release/simd_performance build/.objs/simd_performance/linux/x86_64/release/src/AVXCalculator.cc.o build/.objs/simd_performance/linux/x86_64/release/src/main.cc.o build/.objs/simd_performance/linux/x86_64/release/src/SSECalculator.cc.o $(simd_performance_LDFLAGS) > build/.build.log 2>&1

build/.objs/simd_performance/linux/x86_64/release/src/AVXCalculator.cc.o: src/AVXCalculator.cc
	@echo compiling.release src/AVXCalculator.cc
	@mkdir -p build/.objs/simd_performance/linux/x86_64/release/src
	@$(CXX) -c $(simd_performance_CXXFLAGS) -o build/.objs/simd_performance/linux/x86_64/release/src/AVXCalculator.cc.o src/AVXCalculator.cc > build/.build.log 2>&1

build/.objs/simd_performance/linux/x86_64/release/src/main.cc.o: src/main.cc
	@echo compiling.release src/main.cc
	@mkdir -p build/.objs/simd_performance/linux/x86_64/release/src
	@$(CXX) -c $(simd_performance_CXXFLAGS) -o build/.objs/simd_performance/linux/x86_64/release/src/main.cc.o src/main.cc > build/.build.log 2>&1

build/.objs/simd_performance/linux/x86_64/release/src/SSECalculator.cc.o: src/SSECalculator.cc
	@echo compiling.release src/SSECalculator.cc
	@mkdir -p build/.objs/simd_performance/linux/x86_64/release/src
	@$(CXX) -c $(simd_performance_CXXFLAGS) -o build/.objs/simd_performance/linux/x86_64/release/src/SSECalculator.cc.o src/SSECalculator.cc > build/.build.log 2>&1

clean:  clean_simd_performance

clean_simd_performance: 
	@rm -rf build/linux/x86_64/release/simd_performance
	@rm -rf build/linux/x86_64/release/simd_performance.sym
	@rm -rf build/.objs/simd_performance/linux/x86_64/release/src/AVXCalculator.cc.o
	@rm -rf build/.objs/simd_performance/linux/x86_64/release/src/main.cc.o
	@rm -rf build/.objs/simd_performance/linux/x86_64/release/src/SSECalculator.cc.o

